query ($node: String!) {
  nodeById(id: $node) {
    __typename
    entityId
    entityBundle
    entityPublished
    title
    ... on NodeArticle {
      body {
        processed
      }
    }
  }
}
