#!/usr/bin/env bash

#: exec_target = cli

## Initialize/reinstall site
##
## Usage: fin init-site

# Abort if anything fails
set -e

#-------------------------- Settings --------------------------------

# PROJECT_ROOT and DOCROOT are set as env variables in cli
SITE_DIRECTORY="default"
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
SITEDIR_PATH="${DOCROOT_PATH}/sites/${SITE_DIRECTORY}"

#-------------------------- END: Settings --------------------------------

#-------------------------- Helper functions --------------------------------

# Copy a settings file.
# Skips if the destination file already exists.
# @param $1 source file
# @param $2 destination file
copy_settings_file()
{
	local source="$1"
	local dest="$2"

	if [[ ! -f $dest ]]; then
		echo "Copying ${dest}..."
		cp $source $dest
	else
		echo "${dest} already in place."
	fi
}

#-------------------------- END: Helper functions --------------------------------

#-------------------------- Functions --------------------------------

# Initialize local settings files
init_settings ()
{
	# Copy from settings templates
	copy_settings_file "${SITEDIR_PATH}/default.settings.local.php" "${SITEDIR_PATH}/settings.local.php"

	# Copy bash aliases
	copy_settings_file "${PROJECT_ROOT}/.docksal/bash_aliases.sh" "/home/docker/.bash_aliases"
}

# Fix file/folder permissions
fix_permissions ()
{
	echo "Making site directory writable..."
	chmod 755 "${SITEDIR_PATH}"
	echo
}

# Install site
site_install ()
{
	# Installting binaries
	sudo apt-get install tree jpegoptim optipng pngcrush pngquant libjpeg-progs -y

	# cd to Docroot
	cd $DOCROOT_PATH

	# Composer
	echo
	echo -e "${yellow}Installing composer packages...${NC}"
	echo
	composer install

	# Import the latest db
	echo
	echo -e "${yellow}Importing db...${NC}"
	echo
	drush sql-cli < ${PROJECT_ROOT}/drupal/db_dump/headless.sql

	# Importing configuration
	echo
	echo -e "${yellow}Importing configuration...${NC}"
	echo
	drush cim -y

	# Clear cache
	echo
	echo -e "${yellow}Clearing cache...${NC}"
	echo
	drush cr
}

#-------------------------- END: Functions --------------------------------

#-------------------------- Execution --------------------------------

# Project initialization steps
fix_permissions
init_settings
time site_install

#-------------------------- END: Execution --------------------------------
