fragment Images on ParagraphImages {
  id
  fieldImage {
    media: entity {
      ... on MediaImage {
        image: fieldMediaImage {
          ResponsiveImageStructured(style: wide)
        }
      }
    }
  }
}
